scalar Upload

type User {
  id: ID!
  name: String!
  bio: String
  anonymous: Boolean!
  avatar: Image
  banner: Image
  stories: [Story!]
}

input updateUserArgs {
  bio: String
  anonymous: Boolean!
  avatar: Upload
  banner: Upload
  avatarState: UpdateImageState!
  bannerState: UpdateImageState!
}

type UserResponse implements Response {
  status: Int!
  user: User
}

type Query {
  getUser: UserResponse!
}

type Mutation {
  updateUser(args: updateUserArgs!): GeneralResponse!
  deleteUser: GeneralResponse!
}
